name: metku_dev

dependencies:
 - python=3.11
 - conda-forge::numpy=1.24.2
 - conda-forge::scipy=1.10.1
 - matplotlib=3.7.0
 - spyder=5.4.2
 - pip=23.0.1
 - pip:
   - treelib==1.6.1
   - deap==1.3.3
   - ortools==9.6.*